apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y585pqnfv-python 
  janus-idp.io/tekton: y585pqnfv-python
  backstage.io/kubernetes-id: y585pqnfv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y585pqnfv-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  